sudo: required

services:
  - docker

env:
  matrix:
    - PROJECT=bitcoin
    - PROJECT=bitcoin-unlimited
    - PROJECT=bitcoin-ec

script:
  - ./scripts/snap-in-docker.sh $PROJECT

after_success:
  - openssl aes-256-cbc -K $encrypted_de6cd6e0cc4e_key -iv $encrypted_de6cd6e0cc4e_iv
    -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d

deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t ubuntu:xenial sh -c "apt update -qq && apt
    install snapcraft -y && cd $(pwd) && snapcraft push $PROJECT/*.snap --release
    edge"
  skip_cleanup: true
