sudo: required

services:
  - docker

env:
  matrix:
    - PROJECT=bitcoin ENCRYPTED_KEY=$encrypted_de6cd6e0cc4e_key ENCRYPTED_IV=$encrypted_de6cd6e0cc4e_iv
    - PROJECT=bitcoin-unlimited ENCRYPTED_KEY=$encrypted_9a4f25510385_key ENCRYPTED_IV=$encrypted_9a4f25510385_iv
    - PROJECT=bitcoin-ec ENCRYPTED_KEY=$encrypted_4e5ec7b39439_key ENCRYPTED_IV=$encrypted_4e5ec7b39439_iv

script:
  - ./scripts/snap-in-docker.sh $PROJECT

after_success:
  - mkdir .snapcraft
  - openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV
    -in $PROJECT/.snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d

deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t ubuntu:xenial sh -c "apt update -qq && apt
    install snapcraft -y && cd $(pwd) && snapcraft push $PROJECT/*.snap --release
    edge"
  skip_cleanup: true
