sudo: required

services:
  - docker

env:
  matrix:
    - PROJECT=bitcoin ENCRYPTED_KEY=$encrypted_de6cd6e0cc4e_key ENCRYPTED_IV=$encrypted_de6cd6e0cc4e_iv
    - PROJECT=bitcoin-unlimited ENCRYPTED_KEY=$encrypted_9a4f25510385_key ENCRYPTED_IV=$encrypted_9a4f25510385_iv
    - ONLY_EDGE=1 PROJECT=bitcoin-ec ENCRYPTED_KEY=$encrypted_4e5ec7b39439_key ENCRYPTED_IV=$encrypted_4e5ec7b39439_iv
    - ONLY_EDGE=1 PROJECT=namecoin
    - ONLY_EDGE=1 PROJECT=namecoin-legacy

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget jq

before_script:
  - openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV
    -in $PROJECT/.snapcraft/travis_snapcraft.cfg -out $PROJECT/.snapcraft/snapcraft.cfg -d; echo

script:
  - ./scripts/snap-in-docker.sh $PROJECT

deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq && apt
    install snapcraft -y && cd $(pwd)/$PROJECT && snapcraft push *.snap --release
    edge"
  skip_cleanup: true
