name: namecoin-legacy
version: master
summary: decentralized key/value registration and transfer system (legacy version)
description: |
  Legacy/Classic v0.3.80 Namecoin.
  Namecoin is a decentralized key/value registration and transfer system
  based on Bitcoin technology (a decentralized cryptocurrency).
  It can be used for multiple purposes, for example a secure and
  censorship resistant replacement for DNS.  Ownership of a name
  is based on ownership of a coin, which is in turn based on public key
  cryptography. The namecoin network reaches consensus every few minutes
  as to which names have been reserved or updated.


grade: devel
confinement: strict

apps: #Commands are the same as in namecoin-core. This is intended as they are incompatible with each other.
  daemon:
    command: namecoind
    plugs: [network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
    aliases: [namecoind]
  qt:
    command: desktop-launch namecoin-qt
    plugs: [network, network-bind, unity7]
    aliases: [namecoin-qt]
    desktop: namecoin.desktop
  cli:
    command: namecoin-cli
    aliases: [namecoin-cli]

parts:
  namecoin:
    source: https://github.com/namecoin/namecoin-legacy
    source-type: git
    source-tag: namecoinq-release
    plugin: autotools
    # XXX We don't want to copy the full blockchain every time that the snap is
    # updated, but there's no way to define a default data dir in bitcoin-qt.
    # Also, it would be better if we could split the wallet from the blockchain
    # https://github.com/bitcoin/bitcoin/issues/3214
    # -- elopio-20170308
    prepare: git apply $SNAPCRAFT_STAGE/default_data_dir.patch
    build-packages:
      - g++
      - pkg-config
      - libssl-dev
      - libevent-dev
      - bsdmainutils
      # Boost.
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libboost-thread-dev
      # Optional.
      - libminiupnpc-dev
      - libzmq3-dev
      # GUI.
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      # Optional.
      - libqrencode-dev
    stage-packages: [ca-certificates]
    after:
      - berkeleydb
      - desktop-qt5
      - patches
  berkeleydb:
    source: http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
    plugin: nil
    build: |
      cd build_unix
      ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
    install: |
      cd build_unix
      make install
    prime:
      - -*
  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/gui
    plugin: dump
