name: namecoin-legacy
version: master
summary: decentralized key/value registration and transfer system (legacy version)
description: |
  Legacy/Classic v0.3.80 Namecoin.
  Namecoin is a decentralized key/value registration and transfer system
  based on Bitcoin technology (a decentralized cryptocurrency).
  It can be used for multiple purposes, for example a secure and
  censorship resistant replacement for DNS.  Ownership of a name
  is based on ownership of a coin, which is in turn based on public key
  cryptography. The namecoin network reaches consensus every few minutes
  as to which names have been reserved or updated.


grade: devel
confinement: strict

apps: #Commands are the same as in namecoin-core. This is intended as they are incompatible with each other.
  daemon:
    command: namecoind
    plugs: [network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
    aliases: [namecoind]
  qt:
    command: desktop-launch namecoin-qt
    plugs: [network, network-bind, unity7]
    aliases: [namecoin-qt]
    desktop: namecoin.desktop

parts:
  namecoin:
    source: https://github.com/namecoin/namecoin-legacy
    source-type: git
    source-tag: namecoinq
    plugin: nil
    # XXX We don't want to copy the full blockchain every time that the snap is
    # updated, but there's no way to define a default data dir in bitcoin-qt.
    # Also, it would be better if we could split the wallet from the blockchain
    # https://github.com/bitcoin/bitcoin/issues/3214
    # -- elopio-20170308
    prepare: git apply $SNAPCRAFT_STAGE/*.patch
    build: |
      make -j$(expr $(cat /proc/cpuinfo | grep "^processor" | tail -n 1 | grep "[0-9]*" -o) + 1) -C src INCLUDEPATHS=-I$SNAPCRAFT_STAGE/include LIBPATHS=-L$SNAPCRAFT_STAGE/lib all
      mv ./src/namecoind ./namecoind
      make -C src clean
      BDB_LIB_SUFFIX=-4.8 qmake -makefile
      make -j$(expr $(cat /proc/cpuinfo | grep "^processor" | tail -n 1 | grep "[0-9]*" -o) + 1)
    install: |
      set -ev
      install -Ds ./namecoin-qt $SNAPCRAFT_PART_INSTALL/bin/namecoin-qt
      install -Ds ./namecoind $SNAPCRAFT_PART_INSTALL/bin/namecoind
    build-packages:
      - g++
      - pkg-config
      - libssl-dev
      - libevent-dev
      - bsdmainutils
      # Other.
      - build-essential
      - libgtk2.0-dev
      - libglib2.0-0
      # Boost.
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libboost-thread-dev
      # Optional.
      - libminiupnpc-dev
      - libzmq3-dev
      # GUI.
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      - qt5-default
      - qtchooser
      # Optional.
      - libqrencode-dev
    stage-packages: [ca-certificates]
    after:
      - berkeleydb
      - desktop-qt5
      - patches
#      - wxwidgets
  berkeleydb:
    source: http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
    plugin: nil
    build: |
      cd build_unix
      ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
      make -j$(expr $(cat /proc/cpuinfo | grep "^processor" | tail -n 1 | grep "[0-9]*" -o) + 1)
    install: |
      cd build_unix
      make install
    prime:
      - -*
#  wxwidgets:
#    source: https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2
#    plugin: autotools
#    prime:
#      - -*

  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/gui
    plugin: dump
